name: Build
on: [push]
jobs:
  build:
    name: Build go${{ matrix.go-version }} on ${{ matrix.vm-os }}
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        vm-os: [ubuntu-latest]
        go-version: [1.14]
        # vm-os: [ubuntu-latest, macOS-latest, windows-latest]
        # go-version: [1.12.17, 1.13.8, 1.14]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        shell: bash
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        shell: bash
        run: |
          make ci

      - name: Run
        shell: bash
        run: |
          make run

    # - name: Upload to Codecov
    #   uses: codecov/codecov-action@v1.0.3
    #   with:
    #     token: ${{secrets.codecov_token}}
    #     file: ./coverage.txt
    #   if: startsWith(matrix.vm-os, 'ubuntu')
